version: '3'

services:
  app:
    image: anapsix/alpine-java:8_jdk_unlimited
    ports:
      - '8088:8088'
    volumes:
      - .:/app
    working_dir: /app
    command: './gradlew bootRun'
    environment:
        - GRADLE_USER_HOME=cache
        - SPRING_PROFILES_ACTIVE=dev
  postgresdev:
        image: postgres:9.5
        restart: always
        ports:
         - "5432:5432"
        environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_USER=postgres
         - POSTGRES_DB=pgdev